SPG_Fachtheorie.Aufgabe3Mvc/Models/ErrorViewModel.cs
namespace SPG_Fachtheorie.Aufgabe3Mvc.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SPG_Fachtheorie.Aufgabe3Mvc/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SPG_Fachtheorie.Aufgabe2;
using SPG_Fachtheorie.Aufgabe2.Model;
using SPG_Fachtheorie.Aufgabe3Mvc.Models;
using SPG_Fachtheorie.Aufgabe3Mvc.Services;
using SPG_Fachtheorie.Aufgabe3Mvc.Views.Home;

namespace SPG_Fachtheorie.Aufgabe3Mvc.Controllers;

public class HomeController : Controller
{
    private readonly AppointmentContext _db;
    private readonly AuthService _authService;

    public HomeController(AppointmentContext db, AuthService authService)
    {
        _db = db;
        _authService = authService;
    }

    [HttpGet]
    public IActionResult Index()
    {
        var students = _db.Students.ToList();
        var userItems = students.Select(s => new SelectListItem
        {
            Text = $"{s.Username} - {s.Lastname} {s.Firstname} (Coach: {(s is Coach ? "Ja" : "Nein")})",
            Value = s.Username
        })
        .ToList();

        return View(new IndexViewModel(
            Students: students,
            UserItems: userItems,
            CurrentUser: _authService.Username,
            SelectedUser: _authService.Username));
    }

    [HttpPost]
    public async Task<IActionResult> Index(string selectedUser)
    {
        await _authService.TryLogin(selectedUser);
        return RedirectToAction();
    }

    [HttpPost("logout")]
    public async Task<IActionResult> Logout()
    {
        await _authService.Logout();
        return RedirectToAction("Index");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

SPG_Fachtheorie.Aufgabe3Mvc/Controllers/OffersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SPG_Fachtheorie.Aufgabe2;
using SPG_Fachtheorie.Aufgabe2.Model;
using SPG_Fachtheorie.Aufgabe3Mvc.Services;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace SPG_Fachtheorie.Aufgabe3Mvc.Controllers
{
    public class OffersController : Controller
    {
        private readonly AppointmentContext _db;
        private readonly AuthService _authService;

        public OffersController(AppointmentContext db, AuthService authService)
        {
            _db = db;
            _authService = authService;
        }

        private Guid? IsCoach()
        {
            var student = _db.Students.FirstOrDefault(x => x.Username == _authService.Username);
            if (student is Coach)
                return student.Id;
            else
                return null;
        }

        // GET : Offers
        public IActionResult Index()
        {
            Guid? coachId = IsCoach();
            if (coachId == null)
                return Redirect("/");

            var appointmentContext = _db.Offers
                .Where(x => x.TeacherId == coachId)
                .Include(x => x.Subject)
                .Include(x => x.Appointments);
            return View(appointmentContext);
        }

        //GET : Offers/Details/{Guid}
        public IActionResult Details(Guid? id)
        {
            if (IsCoach == null)
                return Redirect("/");
            if (id == null)
                return NotFound();

            var appointmentContext = _db.Appointments
                .Include(x => x.Student)
                .Where(x => x.OfferId == id);
            return View(appointmentContext);
        }

        //GET : Offers/Add
        [Authorize]
        public IActionResult Create()
        {
            if (IsCoach == null)
                return Redirect("/");
            ViewData["SubjectId"] = new SelectList(_db.Subjects
                .Select(x => new
                {
                    SubjectId = x.Id,
                    Text = x.Term + " - " + x.Name + " - " + x.EducationType
                }), "SubjectId", "Text");
            return View();
        }

        // POST: Offers/Add
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SubjectId,From,To")] Offer offer)
        {
            var coachId = IsCoach();
            if (coachId == null)
                return Redirect("/");
            if (offer.To < DateTime.Now)
                ModelState.AddModelError("To", "Can not create Offers in the past");

            if (!ModelState.IsValid)
            {
                ViewData["SubjectId"] = new SelectList(_db.Subjects.Select(x => new
                {
                    SubjectId = x.Id,
                    Text = x.Term + "-" + x.Name + "-" + x.EducationType
                }), "SubjectId", "Text");
                return View(offer);
            }

            offer.TeacherId = coachId.Value;
            offer.Id = Guid.NewGuid();

            _db.Offers.Add(offer);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));            
        }

        // GET: Offers/Edit/{offerGuid}
        [Authorize]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (IsCoach == null)
                return Redirect("/");
            if (id == null)
                return NotFound();

            var offer = await _db.Offers
                .Include(x => x.Subject)
                .FirstOrDefaultAsync(x => x.Id == id);

            if (offer == null)
                return NotFound();
            return View(offer);
        }

        // POST: Offers/Edit/{offerGuid}
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,To")] Offer offer)
        {
            if (IsCoach() == null)
                return Redirect("/");
            if (id != offer.Id)
                return NotFound();
            if (!ModelState.IsValid)
                return View(offer);

            var dbOffer = await _db.Offers
                .Include(x => x.Subject)
                .FirstOrDefaultAsync(x => x.Id == offer.Id);
            if (dbOffer == null)
                return NotFound();

            if (offer.To < dbOffer.To)
            {
                ModelState.AddModelError("To", "Can not set date before saved date");
                return View(dbOffer);
            }

            dbOffer.To = offer.To;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Offers/Delete/{offerGuid}
        [Authorize]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (IsCoach == null)
                return Redirect("/");
            if (id == null)
                return NotFound();
            var offer = await _db.Offers
                .Include(x => x.Appointments)
                .Include(x => x.Subject)
                .FirstOrDefaultAsync(o => o.Id == id);
            if (offer == null)
                return NotFound();
            return View(offer);
        }

        // POST: Offers/Delete/{offerGuid}
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (IsCoach() == null)
                return Redirect("/");

            var offer = await _db.Offers
                .Include(x => x.Appointments)
                .Include(x => x.Subject)
                .FirstOrDefaultAsync(o => o.Id == id);

            if (offer == null)
                return NotFound();

            if (offer.Appointments.Count > 0)
            {
                ModelState.AddModelError("Appointments", "Offer has Appointments, can therefore not be deleted");
                return View(offer);
            }

            _db.Offers.Remove(offer);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

SPG_Fachtheorie.Aufgabe3Mvc/Views/Home/Index.cshtml
@using SPG_Fachtheorie.Aufgabe2.Model
@model SPG_Fachtheorie.Aufgabe3Mvc.Views.Home.IndexViewModel
<div>
    <h1 class="h3">Klausurprüfung aus Fachtheorie</h1>
    <p>Bitte füllen Sie diese Daten in der Datei <em>SPG_Fachtheorie.Aufgabe3RazorPages/Pages/Index.cshtml</em> am Beginn Ihrer Arbeit aus.</p>
    <table class="table table-sm mb-5 border border-primary">
        <tr>
            <th style="width:10em">Maturaaccount</th>
            <td style="width:30em">(Bitte ausfüllen)</td>
        </tr>
        <tr>
            <th>Vorname</th>
            <td>Matthias</td>
        </tr>
        <tr>
            <th>Zuname</th>
            <td>Holzer</td>
        </tr>
        <tr>
            <th>Klasse</th>
            <td>5CHIF</td>
        </tr>
    </table>
</div>
<div class="mb-3">
    @if (Model.CurrentUser is not null)
    {
        <h5>Angemeldet als User @Model.CurrentUser</h5>
        <form method="post" asp-action="Logout">
            <button class="btn btn-primary">Logout</button>
        </form>

    }
    else
    {
        <h5>
            Wähle einen User aus:
        </h5>
        <form method="post">
            <select asp-for="SelectedUser"
                class="form-control"
                asp-items="Model.UserItems"></select>
            <button class="btn btn-primary">Login</button>
        </form>
    }
</div>
<div>
    <h1 class="h5">Daten der Tabelle Student</h1>
    <p>Diese Tabelle dient zum Testen des Datenbankzugriffes.</p>
</div>
<table class="table table-sm">
    <thead>
        <tr>
            <th>GUID</th>
            <th>Username</th>
            <th>Name</th>
            <th>Rolle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model.Students)
        {
            <tr>
                <td>@s.Id</td>
                <td>@s.Username</td>
                <td>@s.Lastname @s.Firstname</td>
                <td>@(s is Coach ? "Coach" : "Student")</td>
            </tr>
        }
    </tbody>
</table>

SPG_Fachtheorie.Aufgabe3Mvc/Views/Offers/Create.cshtml
@model SPG_Fachtheorie.Aufgabe2.Model.Offer

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Offer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class ="form-control" asp-items="ViewBag.SubjectId"></select>
            </div>
            <div class="form-group">
                <label asp-for="From" class="control-label"></label>
                <input asp-for="From" class="form-control" />
                <span asp-validation-for="From" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="To" class="control-label"></label>
                <input asp-for="To" class="form-control" />
                <span asp-validation-for="To" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SPG_Fachtheorie.Aufgabe3Mvc/Views/Offers/Delete.cshtml
@model SPG_Fachtheorie.Aufgabe2.Model.Offer

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject.Term)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Term)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject.EducationType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.EducationType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.From)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.From)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.To)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.To)
        </dd>
    </dl>
</div>
<h3>Are you sure you want to delete this?</h3>

<form asp-action="Delete">
    <input type="hidden" asp-for="Id"/>
    <span asp-validation-for="Appointments" class="text-danger"></span>
    <input type="submit" value="Delete" class="btn btn-danger"/> |
    <a asp-action="Index">Back to List</a>
</form>

SPG_Fachtheorie.Aufgabe3Mvc/Views/Offers/Details.cshtml
@using SPG_Fachtheorie.Aufgabe2.Model
@model IEnumerable<SPG_Fachtheorie.Aufgabe2.Model.Appointment>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(x => x.Student.Firstname)</th>
            <th>@Html.DisplayNameFor(x => x.Student.Lastname)</th>
            <th>@Html.DisplayNameFor(x => x.Date)</th>
            <th>@Html.DisplayNameFor(x => x.Location)</th>
            <th>@Html.DisplayNameFor(x => x.State)</th>
        </tr>
    </thead>
    <tbody>
        
        @foreach (var appointment in Model)
        {
            var style = appointment.State == AppointmentState.Cancelled ? "background: gray;" : "";
            <tr style="@style">
                <td>@Html.DisplayFor(modelItem => appointment.Student.Firstname)</td>
                <td>@Html.DisplayFor(modelItem => appointment.Student.Lastname)</td>
                <td>@Html.DisplayFor(modelItem => appointment.Date)</td>
                <td>@Html.DisplayFor(modelItem => appointment.Location)</td>
                <td>@Html.DisplayFor(modelItem => appointment.State)</td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Index">Back to Offers</a>
</div>

SPG_Fachtheorie.Aufgabe3Mvc/Views/Offers/Edit.cshtml
@model SPG_Fachtheorie.Aufgabe2.Model.Offer

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Offer</h4>
<hr />
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject.Term)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Term)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject.EducationType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.EducationType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.From)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.From)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.To)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.To)
        </dd>
    </dl>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="To" class="control-label"></label>
                <input asp-for="To" class="form-control" />
                <span asp-validation-for="To" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SPG_Fachtheorie.Aufgabe3Mvc/Views/Offers/Index.cshtml
@model IEnumerable<SPG_Fachtheorie.Aufgabe2.Model.Offer>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Offers</h1>
<table class="table table-sm">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(x => x.Subject.Term)</th>
            <th>@Html.DisplayNameFor(x => x.Subject.Name)</th>
            <th>@Html.DisplayNameFor(x => x.Subject.EducationType)</th>
            <th>@Html.DisplayNameFor(x => x.From)</th>
            <th>@Html.DisplayNameFor(x => x.To)</th>
            <th>@Html.DisplayNameFor(x => x.Appointments.Count)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <th>@Html.DisplayFor(o => x.Subject.Term)</th>
                <th>@Html.DisplayFor(o => x.Subject.Name)</th>
                <th>@Html.DisplayFor(o => x.Subject.EducationType)</th>
                <th>@Html.DisplayFor(o => x.From)</th>
                <th>@Html.DisplayFor(o => x.To)</th>
                <th>@Html.DisplayFor(o => x.Appointments.Count)</th>
            </tr>
            <td>
                <a asp-action="Edit" asp-route-id="@x.Id">Edit</a>
                <a asp-action="Details" asp-route-id="@x.Id">Details</a>
                <a asp-action="Delete" asp-route-id="@x.Id">Delete</a>
            </td>
        }
    </tbody>
</table>
<p> <a asp-action="Create">Create New</a></p>

SPG_Fachtheorie.Aufgabe3Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SPG_Fachtheorie.Aufgabe3Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SPG_Fachtheorie.Aufgabe3Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SPG_Fachtheorie.Aufgabe3Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Offers" asp-action="Index">Offers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SPG_Fachtheorie.Aufgabe3Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>